#!/usr/bin/env bash

set -euo pipefail

: "${DEBUG:=0}"
test "$DEBUG" != "0" && set -x

src_file="$1"

date="$(extract_exif_date "$src_file" 2> /dev/null || extract_filename_date "$src_file" 2> /dev/null || true)"
if [ -z "$date" ]; then
  echo "no date found in filename and exif data for $1" >&2
  exit 1
fi

echo "$date"

