#!/usr/bin/env bash

set -euo pipefail

: "${DEBUG:=0}"
test "$DEBUG" != "0" && set -x

date="$(exiftool -T -DateTimeOriginal "$1" | cut -d ' ' -f 1 | tr ':' ' ')"

if [ "$date" = "-" ]; then
  echo "no date found in exif data of $1" >&2
  exit 1
fi

echo "$date"
