#!/usr/bin/env bash

set -euo pipefail

: ${DEBUG:=0}
test "$DEBUG" != "0" && set -x

date="$(exiftool -T -DateTimeOriginal "$@" | cut -d ' ' -f 1 | tr ':' ' ')"

if [ "$date" = "-" ]; then
  echo "no date found in exif data of $@" >&2
  exit 1
fi

echo "$date"
