version: '3'
services:
  syncthing:
    restart: unless-stopped
    image: "docker.io/syncthing/syncthing:1.27.2"
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    volumes:
      - syncthing_data:/var/syncthing
      - ${UNIXCLOUD_UPLOAD_DIR:-./upload}:/var/syncthing/unixcloud:rw
    networks:
      default:
        aliases:
          - "syncthing.localhost"
    labels:
      - traefik.http.routers.syncthing-unixcloud.rule=Host(`syncthing.${UNIXCLOUD_DOMAIN:-localhost}`)

volumes:
  syncthing_data: {}
